# Generated by Django 4.2.6 on 2023-11-12 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_form1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form1',
            name='name',
        ),
    ]
