# Generated by Django 4.2.6 on 2023-11-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_form1_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.CharField(max_length=1000)),
                ('answer2', models.CharField(max_length=1000)),
                ('answer3', models.CharField(max_length=1000)),
            ],
        ),
    ]
