# Generated by Django 4.2.6 on 2023-11-12 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_form2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form2',
            old_name='answer1',
            new_name='answer4',
        ),
        migrations.RenameField(
            model_name='form2',
            old_name='answer2',
            new_name='answer5',
        ),
        migrations.RenameField(
            model_name='form2',
            old_name='answer3',
            new_name='answer6',
        ),
    ]
